=== HBPNeurorobotics/ExDBackend/hbp_nrp_backend/hbp_nrp_backend/exd_config/ExDConfFile.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<!--Contains a timeline condition -->
<xs:element name="timeline">
  <xs:complexType>
    <xs:sequence>
      <xs:element name="time" type="xs:time"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>

<!--Contains a hardware condition -->
<xs:element name="hardware">
  <xs:complexType>
    <xs:choice>
      <xs:element name="key" type="xs:string"/>
    </xs:choice>
  </xs:complexType>
</xs:element>

<!--Contains a property condition -->
<xs:element name="property">
  <xs:complexType>
    <xs:sequence>
      <xs:element name="identifier" type="xs:string"/>
      <xs:element name="value" type="xs:anyType"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>

<!--Contains a generic condition -->
<xs:element name="condition">
  <xs:complexType>
    <xs:choice>
      <xs:element ref="timeline"/>
      <xs:element ref="hardware"/>
      <xs:element ref="property"/>
    </xs:choice>
  </xs:complexType>
</xs:element>

<!--Contains an or -->
<xs:element name="or">
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="conditions" minOccurs="2" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>

<!--Contains an and -->
<xs:element name="and">
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="conditions" minOccurs="2" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>

<!--Contains actions -->
<xs:element name="actions">
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="property" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>

<!--Contains conditions -->
<xs:element name="conditions">
  <xs:complexType>
    <xs:choice>
      <xs:element ref="and"/>
      <xs:element ref="or"/>
      <xs:element ref="condition"/>
    </xs:choice>
  </xs:complexType>
</xs:element>

<!--Contains a generic event -->
<xs:element name="event">
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="conditions"/>
      <xs:element ref="actions"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>

<!--Contains a pose -->
<xs:element name="pose">
  <xs:complexType>
    <xs:sequence>
      <xs:element name="x" type="xs:double"/>
      <xs:element name="y" type="xs:double"/>
      <xs:element name="z" type="xs:double"/>
      <xs:element name="ux" type="xs:double"/>
      <xs:element name="uy" type="xs:double"/>
      <xs:element name="uz" type="xs:double"/>
      <xs:element name="theta" type="xs:double"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>

<!--Contains a environmentModel -->
<xs:element name="environmentModel">
  <xs:complexType>
    <xs:sequence>
      <xs:element name="location" type="xs:string"/>
      <xs:element ref="pose"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>

<!--Root element of the ExD file -->
<xs:element name="ExD">
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="environmentModel"/>
      <xs:element name="bibiConf" type="xs:string"/>
      <xs:element ref="event" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>
</xs:schema>

=== HBPNeurorobotics/ExDBackend/hbp_nrp_backend/hbp_nrp_backend/exd_config/tests/ExDXMLExample.xml
<?xml version="1.0" encoding="utf-8"?>
<ExD xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ExDConfFile.xsd">
  <environmentModel>"/virtual_room/virtual_room.sdf"</environmentModel>
  <bibiConf>milestone2.xml</bibiConf>
  <event>
    <conditions>
      <condition>
        <timeline>
          <time>00:00:00</time>
        </timeline>
      </condition>
    </conditions>
    <actions>
      <property>
        <identifier>&lt;model name=&quot;husky&quot;&gt;&lt;pose /&gt;&lt;/model&gt;</identifier>
        <value>0 0 .5 0 0 0</value>
      </property>
    </actions>
  </event>
  <event>
    <conditions>
      <and>
        <conditions>
          <condition>
            <hardware>
              <key>X</key>
            </hardware>
          </condition>
        </conditions>
        <conditions>
          <condition>
            <property>
              <identifier>&lt;model name=&quot;right_vr_screen&quot;&gt;&lt;link name=&quot;body&quot;&gt;&lt;visual name=&quot;screen_glass&quot;&gt;&lt;material /&gt;&lt;script /&gt;&lt;name /&gt;&lt;/visual&gt;&lt;/link&gt;&lt;/model&gt;</identifier>
              <value>Gazebo/Blue</value>
            </property>
          </condition>
        </conditions>
      </and>
    </conditions>
    <actions>
      <property>
        <identifier>&lt;model name=&quot;right_vr_screen&quot;&gt;&lt;link name=&quot;body&quot;&gt;&lt;visual name=&quot;screen_glass&quot;&gt;&lt;material /&gt;&lt;script /&gt;&lt;name /&gt;&lt;/visual&gt;&lt;/link&gt;&lt;/model&gt;</identifier>
        <value>Gazebo/Red</value>
      </property>
    </actions>
  </event>
  <event>
    <conditions>
      <and>
        <conditions>
          <condition>
            <hardware>
              <key>Y</key>
            </hardware>
          </condition>
        </conditions>
        <conditions>
          <condition>
            <property>
              <identifier>&lt;model name=&quot;right_vr_screen&quot;&gt;&lt;link name=&quot;body&quot;&gt;&lt;visual name=&quot;screen_glass&quot;&gt;&lt;material /&gt;&lt;script /&gt;&lt;name /&gt;&lt;/visual&gt;&lt;/link&gt;&lt;/model&gt;</identifier>
              <value>Gazebo/Red</value>
            </property>
          </condition>
        </conditions>
      </and>
    </conditions>
    <actions>
      <property>
        <identifier>&lt;model name=&quot;right_vr_screen&quot;&gt;&lt;link name=&quot;body&quot;&gt;&lt;visual name=&quot;screen_glass&quot;&gt;&lt;material /&gt;&lt;script /&gt;&lt;name /&gt;&lt;/visual&gt;&lt;/link&gt;&lt;/model&gt;</identifier>
        <value>Gazebo/Blue</value>
      </property>
    </actions>
  </event>
</ExD>
