=== HBPNeurorobotics/ExDBackend/hbp_nrp_backend/hbp_nrp_backend/bibi_config/bibi_configuration.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://schemas.humanbrainproject.eu/SP10/2014/BIBI"
           xmlns="http://schemas.humanbrainproject.eu/SP10/2014/BIBI"
           attributeFormDefault="unqualified" elementFormDefault="qualified">

  <!--Root element of the bibi file -->
  <xs:element name="bibi" type="BIBIConfiguration"/>
  <xs:complexType name="BIBIConfiguration">
    <xs:sequence>
      <xs:element name="brainModel" type="H5_Filename"/>
      <xs:element name="bodyModel" type="SDF_Filename"/>
      <xs:element name="transferFunction" type="TransferFunction" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element name="transferFunctionImport" type="Python_Filename" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <xs:simpleType name="SDF_Filename">
    <xs:restriction base="xs:string">
      <xs:pattern value="[a-zA-Z0-9\._/]*\.sdf"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="H5_Filename">
    <xs:restriction base="xs:string">
      <xs:pattern value="[a-zA-Z0-9\._/]*\.h5"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="Python_Filename">
    <xs:restriction base="xs:string">
      <xs:pattern value="[a-zA-Z0-9\._/]*\.py"/>
    </xs:restriction>
  </xs:simpleType>

  <!--contains a transfer function element with input, output and used transfer function-->
  <xs:complexType name="TransferFunction" abstract="true">
    <xs:sequence>
      <xs:element name="local" type="Local" minOccurs="0" maxOccurs="unbounded"/>      
    </xs:sequence>
    <xs:attribute name="name" type="xs:string"/>
  </xs:complexType>
  
  <xs:complexType name="Robot2Neuron">
    <xs:complexContent>
      <xs:extension base="TransferFunction">
        <xs:sequence>
          <xs:choice minOccurs="1" maxOccurs="unbounded">
            <xs:element name="device" type="DeviceChannel"/>
            <xs:element name="deviceGroup" type="DeviceGroupChannel"/>
          </xs:choice>
          <xs:element name="topic" type="RobotTopic" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  
  <xs:complexType name="Neuron2Robot">
    <xs:complexContent>
      <xs:extension base="TransferFunction">
        <xs:sequence>
          <xs:choice minOccurs="1" maxOccurs="unbounded">
            <xs:element name="device" type="DeviceConfiguration"/>
            <xs:element name="deviceGroup" type="DeviceGroupConfiguration"/>
          </xs:choice>
          <xs:element name="topic" type="TopicChannel" minOccurs="1" maxOccurs="1"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="DeviceConfiguration">
    <xs:sequence>
      <xs:element name="neurons" type="NeuronSelector" minOccurs="1"/>
    </xs:sequence>
    <xs:attribute name="name" type="xs:string" use="required"/>
    <xs:attribute name="type" type="DeviceType" use="required"/>
  </xs:complexType>

  <xs:complexType name="DeviceChannel">
    <xs:complexContent>
      <xs:extension base="DeviceConfiguration">
        <xs:sequence>
          <xs:element name="body" type="FlowExpression" minOccurs="0" maxOccurs="1"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="DeviceGroupConfiguration">
    <xs:sequence>
      <xs:element name="neurons" type="NeuronSelector" minOccurs="1"/>
    </xs:sequence>
    <xs:attribute name="name" type="xs:string" use="required"/>
    <xs:attribute name="type" type="DeviceType" use="required"/>
  </xs:complexType>

  <xs:complexType name="DeviceGroupChannel">
    <xs:complexContent>
      <xs:extension base="DeviceGroupConfiguration">
        <xs:sequence>
          <xs:element name="body" type="FlowExpression" minOccurs="0" maxOccurs="1"/>          
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="NeuronSelector" abstract="true">
    <xs:attribute name="population" type="xs:string"/>
  </xs:complexType>
  
  <xs:complexType name="Index">
    <xs:complexContent>
      <xs:extension base="NeuronSelector">
        <xs:attribute name="index" type="xs:nonNegativeInteger" use="required"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="Range">
    <xs:complexContent>
      <xs:extension base="NeuronSelector">
        <xs:attribute name="from" type="xs:nonNegativeInteger" use="required"/>
        <xs:attribute name="to" type="xs:nonNegativeInteger" use="required"/>
        <xs:attribute name="step" type="xs:nonNegativeInteger" use="optional"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:simpleType name="DeviceType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="ACSource"/>
      <xs:enumeration value="DCSource"/>
      <xs:enumeration value="FixedFrequency"/>
      <xs:enumeration value="LeakyIntegratorAlpha"/>
      <xs:enumeration value="LeakyIntegratorExp"/>
      <xs:enumeration value="NCSource"/>
      <xs:enumeration value="Poisson"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="RobotTopic">
    <xs:sequence>
    </xs:sequence>
    <xs:attribute name="name" type="xs:string"/>
    <xs:attribute name="topic" type="RobotTopicAddress"/>
    <xs:attribute name="type" type="xs:string"/>
  </xs:complexType>

  <xs:complexType name="TopicChannel">
    <xs:complexContent>
      <xs:extension base="RobotTopic">
        <xs:sequence>
          <xs:element name="body" type="FlowExpression" minOccurs="0" maxOccurs="1"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:simpleType name="RobotTopicAddress">
    <xs:restriction base="xs:string">
      <xs:pattern value="(/[a-zA-Z0-9_-]+)+(/)?"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="FlowExpression" abstract="true">
  </xs:complexType>

  <xs:complexType name="Scale">
    <xs:complexContent>
      <xs:extension base="FlowExpression">
        <xs:sequence>
          <xs:element name="inner" type="FlowExpression"/>
        </xs:sequence>
        <xs:attribute name="factor" type="xs:double"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="Call">
    <xs:complexContent>
      <xs:extension base="FlowExpression">
        <xs:sequence>
          <xs:element name="argument" type="Argument" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="type" type="xs:string"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="Operator" abstract="true">
    <xs:complexContent>
      <xs:extension base="FlowExpression">
        <xs:sequence>
          <xs:element name="operand" type="FlowExpression" minOccurs="2" maxOccurs="unbounded"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="Add">
    <xs:complexContent>
      <xs:extension base="Operator"/>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="Subtract">
    <xs:complexContent>
      <xs:extension base="Operator"/>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="Multiply">
    <xs:complexContent>
      <xs:extension base="Operator"/>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="Divide">
    <xs:complexContent>
      <xs:extension base="Operator"/>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="Min">
    <xs:complexContent>
      <xs:extension base="Operator"/>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="Max">
    <xs:complexContent>
      <xs:extension base="Operator"/>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="Argument">
    <xs:sequence>
      <xs:element name="value" type="FlowExpression" minOccurs="1"/>
    </xs:sequence>
    <xs:attribute name="name" type="xs:string" use="required"/>
  </xs:complexType>

  <xs:complexType name="Local">
    <xs:sequence>
      <xs:element name="body" type="FlowExpression" minOccurs="1"/>
    </xs:sequence>
    <xs:attribute name="name" type="xs:string" use="required"/>
  </xs:complexType>

  <xs:complexType name="ArgumentReference">
    <xs:complexContent>
      <xs:extension base="FlowExpression">
        <xs:attribute name="name" type="xs:string" use="required"/>
        <xs:attribute name="property" type="xs:string" use="optional"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="Constant">
    <xs:complexContent>
      <xs:extension base="FlowExpression">
        <xs:attribute name="value" type="xs:double" use="required"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
</xs:schema>

=== HBPNeurorobotics/ExDBackend/hbp_nrp_backend/hbp_nrp_backend/bibi_config/tests/milestone2.xml
<?xml version="1.0" encoding="UTF-8"?>
<bibi xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schemas.humanbrainproject.eu/SP10/2014/BIBI" xsi:schemaLocation="http://schemas.humanbrainproject.eu/SP10/2014/BIBI bibi_configuration.xsd">
  <brainModel>circuit.h5</brainModel>
  <bodyModel>husky.sdf</bodyModel>
  <transferFunction xsi:type="Neuron2Robot" name="linear_twist">
    <device name="left_wheel_neuron" type="LeakyIntegratorAlpha">
      <neurons xsi:type="Index" population="actors" index="1"/>
    </device>
    <device name="right_wheel_neuron" type="LeakyIntegratorAlpha">
      <neurons xsi:type="Index" population="actors" index="2"/>
    </device>
    <topic name="wheel" topic="/husky/cmd_vel" type="geometry_msgs.msg.Twist">
      <body xsi:type="Call" type="geometry_msgs.msg.Twist">
        <argument name="linear">
          <value xsi:type="Call" type="geometry_msgs.msg.Vector3">
            <argument name="x">
              <value xsi:type="Scale" factor="500">
                <inner xsi:type="Min">
                  <operand xsi:type="ArgumentReference" name="left_wheel_neuron" property="voltage"/>
                  <operand xsi:type="ArgumentReference" name="right_wheel_neuron" property="voltage"/>
                </inner>
              </value>
            </argument>
            <argument name="y">
              <value xsi:type="Constant" value="0"/>
            </argument>
            <argument name="z">
              <value xsi:type="Constant" value="0"/>
            </argument>
          </value>
        </argument>
        <argument name="angular">
          <value xsi:type="Call" type="geometry_msgs.msg.Vector3">
            <argument name="x">
              <value xsi:type="Constant" value="0"/>
            </argument>
            <argument name="y">
              <value xsi:type="Constant" value="0"/>
            </argument>
            <argument name="z">
              <value xsi:type="Scale" factor="1500">
                <inner xsi:type="Subtract">
                  <operand xsi:type="ArgumentReference" name="left_wheel_neuron" property="voltage"/>
                  <operand xsi:type="ArgumentReference" name="right_wheel_neuron" property="voltage"/>
                </inner>
              </value>
            </argument>
          </value>
        </argument>
      </body>
    </topic>
  </transferFunction>
  <transferFunction xsi:type="Robot2Neuron" name="eye_sensor_transmit">
    <local name="image_results">
      <body xsi:type="Call" type="python_cle.tf_framework.tf_lib.detect_red">
        <argument name="image">
          <value xsi:type="ArgumentReference" name="camera" property="value"/>
        </argument>
      </body>
    </local>
    <device name="red_left_eye" type="Poisson">
      <neurons xsi:type="Index" population="sensors" index="0"/>
      <body xsi:type="Scale" factor="0.002">
        <inner xsi:type="ArgumentReference" name="image_results" property="left"/>
      </body>
    </device>
    <device name="red_right_eye" type="Poisson">
      <neurons xsi:type="Index" population="sensors" index="1"/>
      <body xsi:type="Scale" factor="0.002">
        <inner xsi:type="ArgumentReference" name="image_results" property="right"/>
      </body>
    </device>
    <device name="green_blue_eye" type="Poisson">
      <neurons xsi:type="Index" population="sensors" index="2"/>
      <body xsi:type="Scale" factor="0.00025">
        <inner xsi:type="ArgumentReference" name="image_results" property="go_on"/>
      </body>
    </device>
    <topic name="camera" topic="/husky/camera" type="sensor_msgs.msg.Image"/>
  </transferFunction>
</bibi>
